### ISSUE TITLE
problem of bcc 

### ISSUE THREAD

**Issue by allaismail** [AirVantage/sbulb#36]
i have this issue even though i have installed bcc in ubuntu 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/alla/Bureau/loadbalancer/sbulb/sbulb/__init__.py", line 2, in <module>
    from bcc import BPF
ImportError: cannot import name 'BPF'

**Comment by sbernard31** [comment]
Maybe you didn't install : bcc package and linux kernel headers ?
=> https://github.com/AirVantage/sbulb#requirements--dependencies
=> https://stackoverflow.com/questions/64046700/bcc-importerror-cannot-import-name-bpf
